{
 "title": "BookSync Backend Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "200, 400 and 500 requests",
   "type": "timeseries",
   "description": "Total 200, 400 and 500 requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_response_codes_total{status_code=~\"2..\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_response_codes_total{status_code=~\"4..\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "http_response_codes_total{status_code=~\"5..\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests in each service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (job)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logged in users",
   "type": "stat",
   "description": "Total number of logged in users",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests in all endpoints",
   "type": "timeseries",
   "description": "Lists the count of requests from all endpoints in all services",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (job, route)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cpu utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency across services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}