receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  influxdb:
    endpoint: "http://influxdb:8086"
    token: "admin123"
    org: "book-sync-org"
    bucket: "monitoring-bucket"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
