global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth:5000"]
  - job_name: "books"
    static_configs:
      - targets: ["books:5001"]
  - job_name: "borrow"
    static_configs:
      - targets: ["borrow:5002"]
  - job_name: "telegraf"
    static_configs:
      - targets: ["telegraf:9273"]

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?bucket=monitoring-bucket&org=book-sync-org"
    bearer_token: "admin123"
